global:
  scrape_interval: 1s # How often to scrape targets by default.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "/etc/prometheus/alerts/application_alerts.yml"
  - "/etc/prometheus/record_rules/record_rule.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "demo"
    static_configs:
      - targets: ["host.docker.internal:9000"]