{
 "title": "Demo Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Service Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(api_request_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate / API",
   "type": "timeseries",
   "description": "Request Rate / API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(func) (rate(api_request_count_total[$__rate_interval]))",
     "legendFormat": "{{func}}"
    }
   ]
  },
  {
   "title": "Request Count Total / API",
   "type": "bargauge",
   "description": "Request Count Total / API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (func, status) (increase(api_request_histogram_bucket[$__range]))",
     "legendFormat": "[{{status}}] {{func}}"
    }
   ]
  },
  {
   "title": "Request Status Count Total",
   "type": "bargauge",
   "description": "Request Status Count Total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(api_request_histogram_bucket[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Latency P95",
   "type": "timeseries",
   "description": "API Request Latency P95",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(func, le, status) (rate(api_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "[{{status}}] {{func}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "JVM Memory Summary",
   "type": "timeseries",
   "description": "JVM Memory Summary",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(area) (jvm_memory_bytes_used)",
     "legendFormat": "[used] {{area}}"
    },
    {
     "expr": "avg by(area) (jvm_memory_bytes_committed)",
     "legendFormat": "[committed] {{area}}"
    },
    {
     "expr": "avg by(area) (jvm_memory_bytes_max)",
     "legendFormat": "[max] {{area}}"
    },
    {
     "expr": "avg by(area) (jvm_memory_bytes_init)",
     "legendFormat": "[init] {{area}}"
    }
   ]
  },
  {
   "title": "Active Connection to Server",
   "type": "gauge",
   "description": "Number of active connections to the server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_connections", "legendFormat": "__auto" }
   ]
  }
 ]
}