groups:
  - name: example-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(api_request_count_total{func="random"}[30s]) > 0.2
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "High request rate detected"
          description: "Request rate is above 0.2 req/s for 30 seconds."
      - alert: HighAPIErrorRate
        expr: api_error_rate:rate5m > 0.05
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High API Error Rate"
          description: "API error rate is above 5% (current value: {{ $value }})"